apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: react-frontend
  title: Apex React Frontend
  description: React SPA with MSAL authentication hosted on Azure Static Web Apps
  annotations:
    backstage.io/techdocs-ref: dir:.
    dev.azure.com/project: apex-platform
    dev.azure.com/build-definition: react-frontend
  tags:
    - react
    - typescript
    - azure-static-web-apps
    - frontend
spec:
  type: website
  lifecycle: production
  owner: group:platform-engineering
  system: apex-platform
